### ISSUE TITLE
Joystick Hats Support

### ISSUE THREAD

**Issue by zi-ree** [janoc/libndofdev#7]
Hi!

I am currently looking into the NDOF support for Firestorm, and I noticed that my XBox 360 pad's D-Pad isn't supported by libndofdev. The D-Pad gets recognized by SDL as a Joystick Hat, so I added support for that to libndofdev in my fork. This works fine for Linux, but I assume it won't do anything for other OSes.

So my question would be: Are hats recognized in the SL viewers at all on Windows / OSX? And should I expose hats as its own data field or map them to additional axes?

Any insight is greatly appreciated!
Thanks!

**Comment by janoc** [comment]
Hello, 

I don't believe SL supports hats in any specific way, the only thing the viewers support are buttons and axes. So if you want to support a hat it would be probably best to map it to axes. 

Re Windows - no idea, I am not Windows users. However, from what I remember, the libndofdev library **is not** used for handling joysticks/gamepads in Windows - the library is from 3D Connexion/Logitech and used to deal with SpaceNavigator devices. 

The code in this repo is a drop-in replacement for it in Linux because Logitech doesn't support Linux at all. And I have added the SDL/joystick support there because it was easy to do and allowed testing even to people without the 3D Connexion hardware. 

However, if you want to add more advanced joystick support to SL then this library likely isn't the right place for it. It is really bending over backwards to emulate the 3D Connexion API. 

BTW, if you have an improvement or a patch I would appreciate a pull request. It is much easier to get things into the various viewers if both Lindens and e.g. Firestorm developers have one place to pull the changes from. Otherwise they will ship ancient broken versions that they forked in-house, patched up and never updated, resulting in broken viewers.

**Comment by zi-ree** [comment]
Thank you for the quick response!

I know there currently is no hat support, that's why I got into it in the fist place :) My idea was to extend joystick/ndof support a bit so we can use gamepads and map buttons/axes so the user can choose how things should work. It sounds like it might be better to switch to pure evdev code in the long run if I want to achieve this. Is that a reasonable thought?

**Comment by janoc** [comment]
Well, if you want to add control mapping feature then SDL is fine and will save you hassle on other platforms (and SL uses it already anyway, so no extra dependency, AFAIK). No need to go with evdev unless you want to support something exotic that SDL doesn't handle. 

My point was more that if you want to add such extra functionality, then that should be integrated directly into the viewer itself and not hacked into libndofdev which is for emulating the SpaceNavigator and Linux-specific. You will need a way to configure things as well and any sort of GUI certainly does not belong in libndofdev. That would be the completely wrong place to put it, introducing inapropriate dependencies too. 

A much better solution would be to extend the "Joystick configuration" window in the viewer and integrate any control mapping code there.

**Comment by zi-ree** [comment]
Absolutely! Any extension I end up making would be inside the viewer code itself. The only thing I was missing was Hats support. But I agree, it might not be the right place to put it into libndovdev. So I might move to an SDL based solution for Linux. Thank you again for your time and insight, and all your help with the library!

**Comment by janoc** [comment]
Well, to be clear - if all you want is to have the hat supported as an axis/button, then that part can be included in libndofdev so that it works transparently for the viewer. If you need to extend libndofdev to make that work, feel free to submit a PR, I will be happy to merge it.

However, I thought d-pads/hats were treated as buttons/axes by SDL already? Maybe I am wrong on this one, I don't have a joystick with a true hat here, only gamepads with a d-pad. 

Anything else - GUI, rebinding of inputs, etc. should go directly in the viewer.

**Comment by zi-ree** [comment]
Hats are treated separately, so I can access them like that. I'll revise my changes and see if/how I can map them to axes, then submit a PR. Thanks again! :)

**Comment by janoc** [comment]
OK, looking forward to the PR!

Good luck and thanks!

**Comment by janoc** [comment]
OK, I have merged your PR #8, I will make a new release and ping the Firestorm devs to update their copy for the future Firestorm release.

Thanks a lot!
